<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 2008 R2" host="NEWVOE0-QTPWS15"><DocLocation><![CDATA[C:\VATS Automation Sanity\Automation\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[NewCo_Ankita1_9i28i2018 6i33i34 AM]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[TestSetExec]]></AName>
<Action rID="T4">
<AName><![CDATA[ExecuteTestCases]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Start]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Start" started.]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:42]]></Time>
<TimeTick>1538112822</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Start]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LogMessage]]></Obj>
<Details plainTxt="False" ><![CDATA[============================Start of the TestCase 'PostpayCBU'===============================================]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:42]]></Time>
<TimeTick>1538112822</TimeTick>
<NodeArgs eType="User" icon="6" nRep="9" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[LogMessage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LogMessage]]></Obj>
<Details plainTxt="False" ><![CDATA[Executing the LoginToSiebel_fn function]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:42]]></Time>
<TimeTick>1538112822</TimeTick>
<NodeArgs eType="User" icon="6" nRep="10" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[LogMessage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Administrator: C:\Windows\Syst]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:42]]></Time>
<TimeTick>1538112822</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Administrator: C:\Windows\Syst.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:42]]></Time>
<TimeTick>1538112822</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[Administrator: C:\Windows\Syst.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" >
<Disp><![CDATA[Administrator: C:\Windows\Syst]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Server Manager_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:47]]></Time>
<TimeTick>1538112827</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Server Manager_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:47]]></Time>
<TimeTick>1538112827</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[Server Manager_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:49]]></Time>
<TimeTick>1538112829</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run "IEXPLORE.EXE",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IEXPLORE.EXE",3]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:49]]></Time>
<TimeTick>1538112829</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[Run "IEXPLORE.EXE",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="19" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Window ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:52]]></Time>
<TimeTick>1538112832</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" >
<Disp><![CDATA[[ Window ].Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Window ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:52]]></Time>
<TimeTick>1538112832</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" >
<Disp><![CDATA[[ Window ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" status="Passed" >
<Disp><![CDATA[Server Manager_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Certificate Error: Navigation]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:54]]></Time>
<TimeTick>1538112834</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Certificate Error: Navigation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:54]]></Time>
<TimeTick>1538112834</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Continue to this website.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:54]]></Time>
<TimeTick>1538112834</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[Continue to this website.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Continue to this website.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:55]]></Time>
<TimeTick>1538112835</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="31" >
<Disp><![CDATA[Continue to this website.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Continue to this website.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:55]]></Time>
<TimeTick>1538112835</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="33" >
<Disp><![CDATA[Continue to this website.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Security Warning ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:56]]></Time>
<TimeTick>1538112836</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[[ Security Warning ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Yes ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:33:57]]></Time>
<TimeTick>1538112837</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="37" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[[ Yes ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="28" >
<Disp><![CDATA[Certificate Error: Navigation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="27" >
<Disp><![CDATA[Certificate Error: Navigation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:00]]></Time>
<TimeTick>1538112840</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:00]]></Time>
<TimeTick>1538112840</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SWEUserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:00]]></Time>
<TimeTick>1538112840</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="41" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[SWEUserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[SWEUserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:01]]></Time>
<TimeTick>1538112841</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="43" >
<Disp><![CDATA[SWEUserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[SWEUserName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["test_agent_nba_04"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:01]]></Time>
<TimeTick>1538112841</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="45" >
<Disp><![CDATA[SWEUserName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[SWEPassword.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:03]]></Time>
<TimeTick>1538112843</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="47" >
<Disp><![CDATA[SWEPassword.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SWEPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["test_agent_nba_04"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:03]]></Time>
<TimeTick>1538112843</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="49" >
<Disp><![CDATA[SWEPassword.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:05]]></Time>
<TimeTick>1538112845</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="51" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:05]]></Time>
<TimeTick>1538112845</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="53" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:08]]></Time>
<TimeTick>1538112848</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[[ Siebel Call Center ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="40" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="39" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:17]]></Time>
<TimeTick>1538112857</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:17]]></Time>
<TimeTick>1538112857</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[View Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:17]]></Time>
<TimeTick>1538112857</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[My Homepage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:17]]></Time>
<TimeTick>1538112857</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="62" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[My Homepage.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[My Homepage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:18]]></Time>
<TimeTick>1538112858</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="65" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[My Homepage.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[My Homepage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:20]]></Time>
<TimeTick>1538112860</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="68" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[My Homepage.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="16" nRep="61" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[View Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="60" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="59" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center]]></Obj>
<Details plainTxt="False" ><![CDATA[SiebApplication]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:20]]></Time>
<TimeTick>1538112860</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:20]]></Time>
<TimeTick>1538112860</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="70" nType="SiebApplication" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Siebel Call Center]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:20]]></Time>
<TimeTick>1538112860</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="71" nType="SiebApplication" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[Siebel Call Center]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[LogMessage]]></Obj>
<Details plainTxt="False" ><![CDATA[Executing the CreateNewAccount_fn function]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:25]]></Time>
<TimeTick>1538112865</TimeTick>
<NodeArgs eType="User" icon="6" nRep="72" Source="ExecuteTestCases" SourceLine="-1" >
<Disp><![CDATA[LogMessage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:27]]></Time>
<TimeTick>1538112867</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" >
<Disp><![CDATA[[ Siebel Call Center ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[PageTabs.GotoScreen]]></Obj>
<Details plainTxt="False" ><![CDATA["Accounts Screen"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:28]]></Time>
<TimeTick>1538112868</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="76" >
<Disp><![CDATA[PageTabs.GotoScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Accounts]]></Obj>
<Details plainTxt="False" ><![CDATA[SiebScreen]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:29]]></Time>
<TimeTick>1538112869</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[All Accounts]]></Obj>
<Details plainTxt="False" ><![CDATA[SiebView]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:29]]></Time>
<TimeTick>1538112869</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Account Details]]></Obj>
<Details plainTxt="False" ><![CDATA[SiebApplet]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:29]]></Time>
<TimeTick>1538112869</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[New]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:29]]></Time>
<TimeTick>1538112869</TimeTick>
<NodeArgs eType="Replay" icon="23" nRep="80" nType="SiebButton" >
<Disp><![CDATA[New]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:30]]></Time>
<TimeTick>1538112870</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="81" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[New.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:30]]></Time>
<TimeTick>1538112870</TimeTick>
<NodeArgs eType="Replay" icon="23" nRep="82" >
<Disp><![CDATA[New.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:31]]></Time>
<TimeTick>1538112871</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:33]]></Time>
<TimeTick>1538112873</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="86" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:34]]></Time>
<TimeTick>1538112874</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="91" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ UMF Messages Active Popup Applet ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object does not exist]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:36]]></Time>
<TimeTick>1538112876</TimeTick>
<NodeArgs eType="Replay" icon="22" nRep="92" nType="SiebApplet" >
<Disp><![CDATA[[ UMF Messages Active Popup Applet ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:36]]></Time>
<TimeTick>1538112876</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="93" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Account type]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:37]]></Time>
<TimeTick>1538112877</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="94" nType="SiebPicklist" >
<Disp><![CDATA[Account type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:37]]></Time>
<TimeTick>1538112877</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="95" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Account type.ActiveItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:38]]></Time>
<TimeTick>1538112878</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="96" >
<Disp><![CDATA[Account type.ActiveItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Account type.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:38]]></Time>
<TimeTick>1538112878</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="97" >
<Disp><![CDATA[Account type.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:39]]></Time>
<TimeTick>1538112879</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="98" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Account Category]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:39]]></Time>
<TimeTick>1538112879</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="99" nType="SiebPicklist" >
<Disp><![CDATA[Account Category]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:40]]></Time>
<TimeTick>1538112880</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="100" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Account Category.ActiveItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:40]]></Time>
<TimeTick>1538112880</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="101" >
<Disp><![CDATA[Account Category.ActiveItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Account Category.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:40]]></Time>
<TimeTick>1538112880</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="102" >
<Disp><![CDATA[Account Category.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:41]]></Time>
<TimeTick>1538112881</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="103" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Account SubCategory]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:41]]></Time>
<TimeTick>1538112881</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="104" nType="SiebPicklist" >
<Disp><![CDATA[Account SubCategory]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:42]]></Time>
<TimeTick>1538112882</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="105" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Account SubCategory.ActiveItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:42]]></Time>
<TimeTick>1538112882</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="106" >
<Disp><![CDATA[Account SubCategory.ActiveItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Account SubCategory.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:43]]></Time>
<TimeTick>1538112883</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="107" >
<Disp><![CDATA[Account SubCategory.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:43]]></Time>
<TimeTick>1538112883</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="108" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Title]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:44]]></Time>
<TimeTick>1538112884</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="109" nType="SiebPicklist" >
<Disp><![CDATA[Title]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:44]]></Time>
<TimeTick>1538112884</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="110" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Title.ActiveItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:44]]></Time>
<TimeTick>1538112884</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="111" >
<Disp><![CDATA[Title.ActiveItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Title.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:45]]></Time>
<TimeTick>1538112885</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="112" >
<Disp><![CDATA[Title.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Obj>
<Details plainTxt="False" ><![CDATA[180]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:45]]></Time>
<TimeTick>1538112885</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="113" >
<Disp><![CDATA[[ Siebel Call Center ].SetTimeOut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[First name]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:46]]></Time>
<TimeTick>1538112886</TimeTick>
<NodeArgs eType="Replay" icon="25" nRep="114" nType="SiebText" >
<Disp><![CDATA[First name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[First name.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/28/2018 - 6:34:46]]></Time>
<TimeTick>1538112886</TimeTick>
<NodeArgs eType="Replay" icon="25" nRep="115" >
<Disp><![CDATA[First name.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[Last name]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>